In [1]:
import torch 
import torch.nn as nn
import torch.nn.functional as F

import torchvision
import torchvision.transforms as transforms

torch.set_printoptions(linewidth=120)


In [2]:
train_set = torchvision.datasets.FashionMNIST(
    root = './data/FashionMNIST'
    ,train = True
    ,download = True
    ,transform = transforms.Compose([
        transforms.ToTensor()        
    ])
)

Extracting ./data/FashionMNIST\FashionMNIST\raw\train-images-idx3-ubyte.gz to ./data/FashionMNIST\FashionMNIST\raw


Extracting ./data/FashionMNIST\FashionMNIST\raw\train-labels-idx1-ubyte.gz to ./data/FashionMNIST\FashionMNIST\raw


Extracting ./data/FashionMNIST\FashionMNIST\raw\t10k-images-idx3-ubyte.gz to ./data/FashionMNIST\FashionMNIST\raw


Extracting ./data/FashionMNIST\FashionMNIST\raw\t10k-labels-idx1-ubyte.gz to ./data/FashionMNIST\FashionMNIST\raw
Processing...


..\torch\csrc\utils\tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.


Done!


In [21]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
    def forward(self,t):
        t = F.relu(self.conv1(t))
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        t = F.relu(self.conv2(t))
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        t = F.relu(self.fc1(t.reshape(-1,12*4*4)))
        t = F.relu(self.fc2(t))
        t = self.out(t)
        
        return t

In [22]:
torch.set_grad_enabled(False)

In [23]:
network = Network()

In [24]:
sample = next(iter(train_set))

In [25]:
image, label = sample 
image.shape

torch.Size([1, 28, 28])

In [26]:
image.unsqueeze(0).shape # This gives us a batch with size 1

torch.Size([1, 1, 28, 28])

In [27]:
pred = network(image.unsqueeze(0)) # image shape needs to be (batcg_size x in_channels x H x W)

In [28]:
pred.shape

torch.Size([1, 10])

In [29]:
pred

tensor([[ 0.1235, -0.0662, -0.0525,  0.0878, -0.0682,  0.1413, -0.0502, -0.0459, -0.0715,  0.0116]])

In [30]:
label

9

In [31]:
pred.argmax(dim=1)

tensor([5])

In [32]:
F.softmax(pred, dim=1)

tensor([[0.1127, 0.0932, 0.0945, 0.1087, 0.0930, 0.1147, 0.0947, 0.0951, 0.0927, 0.1007]])

In [33]:
F.softmax(pred, dim=1).sum()

tensor(1.0000)

In [34]:
net1 = Network()


In [35]:
net1(image.unsqueeze(0))

tensor([[-0.0747, -0.0127, -0.0237,  0.0434,  0.0735,  0.0679, -0.0709, -0.0146, -0.0342,  0.0367]])

In [36]:
net2 = Network()

In [37]:
net2(image.unsqueeze(0))

tensor([[ 0.0364,  0.0090, -0.0876,  0.0714,  0.0083,  0.0288,  0.0408, -0.1024, -0.1013, -0.1184]])